# Python for Data Science, Level I
### *Session \#6*
---

### Helpful shortcuts
---

**SHIFT** + **ENTER** ----> Execute Cell

**TAB** ----> See autocomplete options

**ESC** then **b** ----> Create Cell 

**ESC** then **dd** ----> Delete Cell

**\[python expression\]?** ---> Explanation of that Python expression

**ESC** then **m** then __ENTER__ ----> Switch to Markdown mode

## I. Pandas Basics

### Warm Ups

---

**Importing pandas:** `import pandas as pd`

In [1]:
import pandas as pd

**Dataframe from CSV:** `df = pd.read_csv("inspections.csv")`

*Note: Input string can be a URL or a local file path*

In [2]:
df = pd.read_csv('https://github.com/patricks1/python-for-data-science/'
                 'raw/master/Session06/inspections.csv')

**First 5 lines of file:** `df.head()`

In [3]:
df.head()

,CAMIS,DBA,BORO,BUILDING,STREET,ZIPCODE,PHONE,CUISINE DESCRIPTION,INSPECTION DATE,ACTION,VIOLATION CODE,VIOLATION DESCRIPTION,CRITICAL FLAG,SCORE,GRADE,GRADE DATE,RECORD DATE,INSPECTION TYPE
0,50058559,PRET A MANGER,MANHATTAN,299,7TH AVE,10001.0,6467280505,American,08/28/2017,Violations were cited in the following area(s).,16E,Caloric content range (minimum to maximum) not...,Not Critical,NaN,NaN,NaN,04/01/2019,Calorie Posting / Initial Inspection
1,50069855,FERRY HOUSE CAFE,MANHATTAN,PIER 11,SOUTH ST,10005.0,9175363918,CafÃ©/Coffee/Tea,11/30/2017,Violations were cited in the following area(s).,05H,"No facilities available to wash, rinse and san...",Critical,94.0,C,11/30/2017,04/01/2019,Pre-permit (Operational) / Re-inspection
2,50072700,MAMA FINA'S,MANHATTAN,167,AVENUE A,10009.0,9172620893,Filipino,07/12/2018,Violations were cited in the following area(s).,04K,Evidence of rats or live rats present in facil...,Critical,9.0,A,07/12/2018,04/01/2019,Pre-permit (Operational) / Re-inspection
3,50047067,STARBUCKS COFFEE #22596,BROOKLYN,154,N 7TH ST,11249.0,7183840152,CafÃ©/Coffee/Tea,07/21/2017,Violations were cited in the following area(s).,16E,Caloric content range (minimum to maximum) not...,Not Critical,NaN,NaN,NaN,04/01/2019,Calorie Posting / Initial Inspection
4,41047349,JENNIFER CAFE,MANHATTAN,67,1 AVENUE,10003.0,9176745443,"Latin (Cuban, Dominican, Puerto Rican, South &...",02/27/2018,Violations were cited in the following area(s).,08A,Facility not vermin proof. Harborage or condit...,Not Critical,20.0,NaN,NaN,04/01/2019,Cycle Inspection / Initial Inspection

In [4]:
df.loc[0]

CAMIS                                                             50058559
DBA                                                          PRET A MANGER
BORO                                                             MANHATTAN
BUILDING                                                               299
STREET                                                             7TH AVE
ZIPCODE                                                            10001.0
PHONE                                                           6467280505
CUISINE DESCRIPTION                                               American
INSPECTION DATE                                                 08/28/2017
ACTION                     Violations were cited in the following area(s).
VIOLATION CODE                                                         16E
VIOLATION DESCRIPTION    Caloric content range (minimum to maximum) not...
CRITICAL FLAG                                                 Not Critical
SCORE                                                                  NaN
GRADE                                                                  NaN
GRADE DATE                                                             NaN
RECORD DATE                                                     04/01/2019
INSPECTION TYPE                       Calorie Posting / Initial Inspection
Name: 0, dtype: object

**Boolean indexing on rows:** `df[df['GRADE'] == 'C']`

**Combining Boolean indexes:** 
```python
a_grade = df['GRADE'] == 'A'
bk = df['BORO'] == 'BROOKLYN'
df[a_grade & bk]
```

## Exercises
---
**1. Apply a Boolean filter to** `CUISINE DESCRIPTION` **to select only the Filipino restaurants. How many inspections were there?** 

Hint: Use the `len()` function.

In [5]:
filipino = df['CUISINE DESCRIPTION'] == "Filipino"

len(df[filipino])

179

**2. Apply Boolean filters to select only rows where the** `CRITICAL FLAG` **column is** `Critical`. **What percentage of all inspections were** `Critical`**?**

Hint: Divide the number of `Critical` rows by the total number

In [6]:
critical = df['CRITICAL FLAG'] == 'Critical'

len(df[critical]) / len(df)

0.5447536292127646

**3. How many inspections are there for Starbucks? What percentage of Starbucks inspections were** `Critical`**?**

Hint: Use the `DBA` column to target Starbucks

In [7]:
star = df['DBA'] == 'STARBUCKS'

len(df[star & critical]) / len(df[star])

0.3354072398190045

**4. What percentage of inspections of restaurant located on either** `BOWERY` **or** `EAST BROADWAY` **streets were critical?**

In [8]:
bowery = df['STREET'] == 'BOWERY'
eb = df['STREET'] == 'EAST BROADWAY'

len(df[(bowery|eb)&critical]) / len(df[bowery|eb])

0.5922014622258327

### Extra Credit
---
**1. Which type of restaurant has a higher percentage of** `Critical` **inspections -- restaurants with a** `CUISINE DESCRIPTION` **of** `'Donuts'` **or** `'Juice, Smoothies, Fruit Salads'`**?**

In [9]:
donuts = df['CUISINE DESCRIPTION'] == 'Donuts'
juice = df['CUISINE DESCRIPTION'] == 'Juice, Smoothies, Fruit Salads'

donut_ratio = len(df[donuts&critical])/len(df[donuts])
juice_ratio = len(df[juice&critical])/len(df[juice])

print("DONUT RATIO: " + str(donut_ratio))
print("JUICE RATIO: " + str(juice_ratio))

DONUT RATIO: 0.471031746031746
JUICE RATIO: 0.5187202178352621

## II. Columns


### Warm Ups
---
**See column data types:** `df.dtypes`

In [10]:
df.dtypes

CAMIS                      int64
DBA                       object
BORO                      object
BUILDING                  object
STREET                    object
ZIPCODE                  float64
PHONE                     object
CUISINE DESCRIPTION       object
INSPECTION DATE           object
ACTION                    object
VIOLATION CODE            object
VIOLATION DESCRIPTION     object
CRITICAL FLAG             object
SCORE                    float64
GRADE                     object
GRADE DATE                object
RECORD DATE               object
INSPECTION TYPE           object
dtype: object

**Aggregate column with Numpy function:** `df['SCORE'].mean()`

**Create new column from existing one:** `df['NEG_SCORE'] = df['SCORE'] * -1`

**Create a dataframe from columns:** 
```python
columns = ['DBA', 'SCORE']
df[columns]
```

In [11]:
columns = ['DBA', 'SCORE']
df[columns]

                            DBA  SCORE
0                 PRET A MANGER    NaN
1              FERRY HOUSE CAFE   94.0
2                   MAMA FINA'S    9.0
3       STARBUCKS COFFEE #22596    NaN
4                 JENNIFER CAFE   20.0
...                         ...    ...
250187         JUICE GENERATION    5.0
250188                COCO THAI   21.0
250189               MCDONALD'S    3.0
250190                 BY CHLOE   17.0
250191              ELDERGREENE   55.0

[250192 rows x 2 columns]

**Sort dataframe ascending/descending based on column:** 
```python
df.sort_values('SCORE')
df.sort_values('SCORE', ascending=False)
```

In [12]:
df.sort_values('SCORE')

,CAMIS,DBA,BORO,BUILDING,STREET,ZIPCODE,PHONE,CUISINE DESCRIPTION,INSPECTION DATE,ACTION,VIOLATION CODE,VIOLATION DESCRIPTION,CRITICAL FLAG,SCORE,GRADE,GRADE DATE,RECORD DATE,INSPECTION TYPE
100835,41691451,ANGELINA,MANHATTAN,37,AVENUE A,10009.0,2125337183,American,09/24/2018,Violations were cited in the following area(s).,10F,Non-food contact surface improperly constructe...,Not Critical,-1.0,NaN,NaN,04/01/2019,Cycle Inspection / Initial Inspection
125321,41677480,FUSION HK BAR-GRILL,MANHATTAN,688,10 AVENUE,10019.0,2129560185,Mexican,10/24/2018,Violations were cited in the following area(s).,06D,"Food contact surface not properly washed, rins...",Critical,-1.0,NaN,NaN,04/01/2019,Cycle Inspection / Initial Inspection
76798,41702880,RAKU IT'S JAPANESE II,MANHATTAN,57,WEST 76 STREET,10023.0,2128731220,Japanese,07/24/2018,Violations were cited in the following area(s).,02G,Cold food item held above 41Âº F (smoked fish ...,Critical,-1.0,B,07/24/2018,04/01/2019,Cycle Inspection / Re-inspection
177692,41234821,GYU-KAKU,MANHATTAN,34,COOPER SQUARE,10003.0,2124752989,Japanese,06/02/2016,Violations were cited in the following area(s).,06D,"Food contact surface not properly washed, rins...",Critical,-1.0,NaN,NaN,04/01/2019,Cycle Inspection / Initial Inspection
209819,50010285,FOOLS GOLD,MANHATTAN,145,E HOUSTON ST,10002.0,2126732337,American,07/15/2015,Violations were cited in the following area(s).,08A,Facility not vermin proof. Harborage or condit...,Not Critical,-1.0,NaN,NaN,04/01/2019,Cycle Inspection / Initial Inspection
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250101,50061007,STEWARTS,BROOKLYN,8518,5TH AVE,11209.0,3474974357,American,04/25/2018,No violations were recorded at the time of thi...,NaN,NaN,Not Applicable,NaN,NaN,NaN,04/01/2019,Administrative Miscellaneous / Initial Inspection
250125,50053228,SUMNER CAFE,BROOKLYN,144,DECATUR ST,11233.0,3474046832,CafÃ©/Coffee/Tea,11/01/2016,No violations were recorded at the time of thi...,NaN,NaN,Not Applicable,NaN,NaN,NaN,04/01/2019,Administrative Miscellaneous / Re-inspection
250163,50059003,VIVI BUBBLE TEA,BROOKLYN,2169,86TH ST,11214.0,7185326561,"Juice, Smoothies, Fruit Salads",06/02/2018,Violations were cited in the following area(s).,15F,NaN,Not Applicable,NaN,NaN,NaN,04/01/2019,Smoke-Free Air Act / Re-inspection
250165,50060875,EL CONDE NUEVO,MANHATTAN,4139,BROADWAY,10033.0,2127810419,Spanish,06/19/2018,Violations were cited in the following area(s).,20F,Current letter grade card not posted.,Not Critical,NaN,NaN,NaN,04/01/2019,Administrative Miscellaneous / Initial Inspection
250171,41002547,MCDONALD'S,MANHATTAN,972,6 AVENUE,10018.0,2122792022,Hamburgers,08/17/2017,Violations were cited in the following area(s).,22C,"Bulb not shielded or shatterproof, in areas wh...",Not Critical,NaN,NaN,NaN,04/01/2019,Administrative Miscellaneous / Initial Inspection

In [13]:
df.sort_values('SCORE', ascending=False)

,CAMIS,DBA,BORO,BUILDING,STREET,ZIPCODE,PHONE,CUISINE DESCRIPTION,INSPECTION DATE,ACTION,VIOLATION CODE,VIOLATION DESCRIPTION,CRITICAL FLAG,SCORE,GRADE,GRADE DATE,RECORD DATE,INSPECTION TYPE
15551,41663270,NOUS LES AMIS RESTAURANT & BAKERY,BROOKLYN,2187,CLARENDON ROAD,11226.0,3476279425,Creole,05/26/2018,Establishment Closed by DOHMH. Violations wer...,08A,Facility not vermin proof. Harborage or condit...,Not Critical,156.0,NaN,NaN,04/01/2019,Cycle Inspection / Initial Inspection
224785,41663270,NOUS LES AMIS RESTAURANT & BAKERY,BROOKLYN,2187,CLARENDON ROAD,11226.0,3476279425,Creole,05/26/2018,Establishment Closed by DOHMH. Violations wer...,02G,Cold food item held above 41Âº F (smoked fish ...,Critical,156.0,NaN,NaN,04/01/2019,Cycle Inspection / Initial Inspection
37837,41663270,NOUS LES AMIS RESTAURANT & BAKERY,BROOKLYN,2187,CLARENDON ROAD,11226.0,3476279425,Creole,05/26/2018,Establishment Closed by DOHMH. Violations wer...,06A,Personal cleanliness inadequate. Outer garment...,Critical,156.0,NaN,NaN,04/01/2019,Cycle Inspection / Initial Inspection
58920,41663270,NOUS LES AMIS RESTAURANT & BAKERY,BROOKLYN,2187,CLARENDON ROAD,11226.0,3476279425,Creole,05/26/2018,Establishment Closed by DOHMH. Violations wer...,06C,Food not protected from potential source of co...,Critical,156.0,NaN,NaN,04/01/2019,Cycle Inspection / Initial Inspection
97876,41663270,NOUS LES AMIS RESTAURANT & BAKERY,BROOKLYN,2187,CLARENDON ROAD,11226.0,3476279425,Creole,05/26/2018,Establishment Closed by DOHMH. Violations wer...,05F,Insufficient or no refrigerated or hot holding...,Critical,156.0,NaN,NaN,04/01/2019,Cycle Inspection / Initial Inspection
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250101,50061007,STEWARTS,BROOKLYN,8518,5TH AVE,11209.0,3474974357,American,04/25/2018,No violations were recorded at the time of thi...,NaN,NaN,Not Applicable,NaN,NaN,NaN,04/01/2019,Administrative Miscellaneous / Initial Inspection
250125,50053228,SUMNER CAFE,BROOKLYN,144,DECATUR ST,11233.0,3474046832,CafÃ©/Coffee/Tea,11/01/2016,No violations were recorded at the time of thi...,NaN,NaN,Not Applicable,NaN,NaN,NaN,04/01/2019,Administrative Miscellaneous / Re-inspection
250163,50059003,VIVI BUBBLE TEA,BROOKLYN,2169,86TH ST,11214.0,7185326561,"Juice, Smoothies, Fruit Salads",06/02/2018,Violations were cited in the following area(s).,15F,NaN,Not Applicable,NaN,NaN,NaN,04/01/2019,Smoke-Free Air Act / Re-inspection
250165,50060875,EL CONDE NUEVO,MANHATTAN,4139,BROADWAY,10033.0,2127810419,Spanish,06/19/2018,Violations were cited in the following area(s).,20F,Current letter grade card not posted.,Not Critical,NaN,NaN,NaN,04/01/2019,Administrative Miscellaneous / Initial Inspection
250171,41002547,MCDONALD'S,MANHATTAN,972,6 AVENUE,10018.0,2122792022,Hamburgers,08/17/2017,Violations were cited in the following area(s).,22C,"Bulb not shielded or shatterproof, in areas wh...",Not Critical,NaN,NaN,NaN,04/01/2019,Administrative Miscellaneous / Initial Inspection

### Exercises
---
**1. Use** `.dtypes` **to check the datatype of the** `ZIPCODE` **column. Oh no! Since some ZIP codes start with a zero, this is not what we want.**

**Load the data again using** `pd.read_csv()`, **but this time after the file name, give it an additional input of** `dtype={"ZIPCODE": str}` **to set the ZIP codes to a their proper type.**

In [14]:
df = pd.read_csv('https://github.com/patricks1/python-for-data-science/'
                 'raw/master/Session06/inspections.csv',
                 dtype={"ZIPCODE": str})

**2. What is the average** `SCORE` **across all inspections?**

In [15]:
df['SCORE'].mean()

19.915540853345455

**3. Which has inspections with a higher average** `SCORE`, **Manhattan or Brooklyn?**

In [16]:
bk = df['BORO'] == 'BROOKLYN'
man = df['BORO'] == 'MANHATTAN'

df[man]['SCORE'].mean()

19.758882986419728

**4. Create a new column** `SMALL_SCORE` **which takes the** `SCORE` **column and divides it by 10.**

In [17]:
df['SMALL_SCORE'] = df['SCORE'] / 10

**5. What is the most common** `STREET` **for inspections to occur on?**

Hint: You can use the Numpy method `.mode()` to get the most frequently occuring value from a column.

In [18]:
df['STREET'].mode()

0    BROADWAY
Name: STREET, dtype: object

### Extra Credit
---
**6. What is the most common** `DBA` **for inspections that are flagged** `Critical`?

In [19]:
df[critical]['DBA'].mode()

0    DUNKIN' DONUTS
Name: DBA, dtype: object

## III. Cleaning Data


### Warm Ups
---

**Contains string:** `starbucks = df['DBA'].str.contains('STARBUCKS', na=False)`

In [20]:
starbucks = df['DBA'].str.contains('STARBUCKS', na=False)

**Starts/ends with:** 
```python 
df['DBA'].str.startswith("THE")
df['DBA'].str.endswith("RESTAURANT")
```

**Overwrite:** `df.loc[starbucks, "DBA"] = "STARBUCKS"`

In [21]:
df.loc[starbucks, 'DBA'] = 'STARBUCKS'

**Rows with/without NaN in column:** 
```python
df['GRADE'].isnull()
df['GRADE'].notnull()
```

**Fill all NaN values in a column:** `df['GRADE'].fillna('NOT RATED')`

**Save to CSV:** `df.to_csv("inspections.csv", index=False)`

In [22]:
df.to_csv('inspections_mod.csv', index=False)

### Exercises
---
**1. Find all the spellings of McDonald's by filtering** `DBA` **to anything that contains** `DONALD`

Hint: You can use the `set()` function on the `DBA` column after to just see unique values

In [23]:
donald = df['DBA'].str.contains('DONALD', na=False)

set(df[donald]['DBA'])

{'MCDONALD AVENUE DINER',
 "MCDONALD'S",
 "MCDONALD'S #11542",
 "MCDONALD'S #13068",
 "MCDONALD'S #23105",
 "MCDONALD'S #3880",
 "MCDONALD'S CORPORATION",
 "MCDONALD'S RESTAURANT",
 "MCDONALD'S RESTAURANTS OF NEW YORK INC",
 'MCDONALDS',
 'MCDONALDS # 18093',
 'MCDONALDS # 6160',
 'MCDONALDS RESTAURANT'}

**2. We don't want to include** `Macdonald Avenue Diner` **so create a second Boolean filter to matches** `DBA` **values that end with** `"DINER"`

In [24]:
ends_with_diner = df['DBA'].str.endswith('DINER', na=False)

safe_donald = ~ends_with_diner&donald

**3. Select the rows that match the** `DONALD` **filter but not the** `DINER` **filter, and overwrite with the string** `"MCDONALDS"` **to standardize the spelling.**

In [25]:
df.loc[safe_donald, 'DBA'] = "MCDONALDS"

**4. Use** `.fillna()` **to create a copy of the** `DBA` **column with an empty string instead of NAs. Overwrite the DBA column with this new version.**

In [26]:
df['DBA'] = df['DBA'].fillna('')

### Extra Credit
---

**1. Many restaurants without a grade were given an inspection score, which can be used to derive a grade. Those that get 0 and 13 points earn an A, those with 14 to 27 points receive a B and those with 28
or more a C.**

**Use boolean indexing to fill in those missing grades that can be derived.**

In [27]:
null_grade = df['GRADE'].isnull()

# Fill in A scores
a_score = df['SCORE'] < 14
should_be_a = null_grade & a_score
df.loc[should_be_a, 'GRADE'] = 'A'

# Fill in B scores
b_score = (14 <= df['SCORE']) & (df['SCORE'] <= 27)
should_be_b = null_grade & b_score
df.loc[should_be_b, 'GRADE'] = 'B'

# Fill in C scores
c_score = 28 < df['SCORE'] 
should_be_c = null_grade & c_score
df.loc[should_be_c, 'GRADE'] = 'C'

In [28]:
df[a_score & null_grade]

,CAMIS,DBA,BORO,BUILDING,STREET,ZIPCODE,PHONE,CUISINE DESCRIPTION,INSPECTION DATE,ACTION,VIOLATION CODE,VIOLATION DESCRIPTION,CRITICAL FLAG,SCORE,GRADE,GRADE DATE,RECORD DATE,INSPECTION TYPE,SMALL_SCORE
24,50061061,KENNEDY'S CHICKEN & GRILL,MANHATTAN,2083,AMSTERDAM AVE,10032,9176248039,Chicken,03/30/2017,Violations were cited in the following area(s).,10F,Non-food contact surface improperly constructe...,Not Critical,13.0,A,NaN,04/01/2019,Pre-permit (Operational) / Initial Inspection,1.3
78,50047801,SUNFLOWER CAFE,MANHATTAN,676,AMSTERDAM AVE,10025,2127993415,American,01/05/2018,Establishment Closed by DOHMH. Violations wer...,06C,Food not protected from potential source of co...,Critical,13.0,A,NaN,04/01/2019,Cycle Inspection / Initial Inspection,1.3
82,50049976,J-PETAL,BROOKLYN,4801,5TH AVE,11220,9179091862,"Ice Cream, Gelato, Yogurt, Ices",06/03/2016,Violations were cited in the following area(s).,06C,Food not protected from potential source of co...,Critical,10.0,A,NaN,04/01/2019,Pre-permit (Non-operational) / Initial Inspection,1.0
89,41632535,CROWN FRIED CHICKEN,BROOKLYN,456,SUTTER AVENUE,11212,7187084524,Chicken,08/21/2017,Violations were cited in the following area(s).,02B,Hot food item not held at or above 140Âº F.,Critical,13.0,A,NaN,04/01/2019,Cycle Inspection / Initial Inspection,1.3
98,50002502,LE REVE,MANHATTAN,125,E 54 ST,10022,2127597777,Middle Eastern,05/19/2018,Violations were cited in the following area(s).,06B,"Tobacco use, eating, or drinking from open con...",Critical,12.0,A,NaN,04/01/2019,Cycle Inspection / Initial Inspection,1.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250133,40935583,FRIED FRANK CAFETERIA,MANHATTAN,1,NEW YORK PLAZA,10004,2128598041,American,08/08/2018,Violations were cited in the following area(s).,04N,Filth flies or food/refuse/sewage-associated (...,Critical,8.0,A,NaN,04/01/2019,Cycle Inspection / Initial Inspection,0.8
250136,41250519,MILANO'S BAR,MANHATTAN,51,EAST HOUSTON STREET,10012,2122268844,"Bottled beverages, including water, sodas, jui...",01/23/2017,Violations were cited in the following area(s).,10F,Non-food contact surface improperly constructe...,Not Critical,11.0,A,NaN,04/01/2019,Cycle Inspection / Initial Inspection,1.1
250138,50077824,HARLEM ALE HOUSE,MANHATTAN,101,W 127TH ST,10027,3476410850,American,10/31/2018,Violations were cited in the following area(s).,04N,Filth flies or food/refuse/sewage-associated (...,Critical,8.0,A,NaN,04/01/2019,Cycle Inspection / Initial Inspection,0.8
250143,50045961,TAI LAI RESTAURANT,BROOKLYN,990,T S BOYLAND ST,NaN,7184987787,Chinese,09/15/2016,Violations were cited in the following area(s).,04M,Live roaches present in facility's food and/or...,Critical,8.0,A,NaN,04/01/2019,Cycle Inspection / Initial Inspection,0.8
250154,41101600,EMPHASIS,BROOKLYN,6820,4 AVENUE,11220,7187481319,American,09/11/2017,Violations were cited in the following area(s).,08A,Facility not vermin proof. Harborage or condit...,Not Critical,11.0,A,NaN,04/01/2019,Cycle Inspection / Initial Inspection,1.1